Repository Trycatch-tv/f1it2-Team-10-Backend, pull requests merged in 2023-06, with the labels that each got.

#3 Refactorización
  citasync/src/main/java/com/api/citasync/controllers/CitaRestController.java
  citasync/src/main/java/com/api/citasync/dto/CitaDto.java
  citasync/src/main/java/com/api/citasync/dto/CitaDtoActualizar.java
  citasync/src/main/java/com/api/citasync/dto/CitaRespuestaDto.java
  citasync/src/main/java/com/api/citasync/dto/CitaSolicitudDto.java
  citasync/src/main/java/com/api/citasync/exceptions/HandlerExceptions.java
  citasync/src/main/java/com/api/citasync/mappers/CitaMapper.java
  citasync/src/main/java/com/api/citasync/models/Cita.java
  citasync/src/main/java/com/api/citasync/repositories/CitaRepository.java
  citasync/src/main/java/com/api/citasync/services/CitaService.java
Labels: enhancement

#6 Cambios donde se modificaron y agregaron comentarios con javadoc.
  citasync/src/main/java/com/api/citasync/controllers/CitaRestController.java
  citasync/src/main/java/com/api/citasync/dto/CitaRespuestaDto.java
  citasync/src/main/java/com/api/citasync/dto/CitaSolicitudDto.java
  citasync/src/main/java/com/api/citasync/exceptions/CitaExistenteException.java
  citasync/src/main/java/com/api/citasync/exceptions/ErrorMessage.java
  citasync/src/main/java/com/api/citasync/exceptions/HandlerExceptions.java
  citasync/src/main/java/com/api/citasync/mappers/CitaMapper.java
  citasync/src/main/java/com/api/citasync/models/Cita.java
  citasync/src/main/java/com/api/citasync/models/Estado.java
  citasync/src/main/java/com/api/citasync/repositories/CitaRepository.java
  citasync/src/main/java/com/api/citasync/services/CitaService.java
Labels: documentation

#7 Se modifico la clase HandlerExceptions por un error, Yeferson Agudelo
  README.md
  citasync/src/main/java/com/api/citasync/exceptions/HandlerExceptions.java
Labels: duplicate

#8 Se crea archivo Dockerfile
  Dockerfile
  citasync/src/main/resources/application.properties
Labels: enhancement
